# GitHub Sponsors
github: theyasssh

# External funding platforms
buy_me_a_coffee: theyasssh
ko_fi: theyasssh

# Custom sponsorship links
custom:
  - "https://buymeacoffee.com/theyasssh"
  - "https://theyasssh.github.io"
